from django.urls import path
from . import views
from . import sets
from . import predicts

urlpatterns = [
    path('', views.DB_home, name='DB_home'),
    path('login/', views.DB_login, name='DB_login'),
    path('logout/', views.DB_logout, name='DB_logout'),
    path('book_info/', views.book_info, name='book_info'),
    path('rent_info/', views.rent_info, name='rent_info'),
    path('search/', views.search, name='search_info'),
    path('DB_book/', views.DB_book, name='book_set'),
    path('DB_rent/', views.DB_rent, name='rent_set'),
    path('DB_except/', views.DB_except, name='except_set'),
    path('dev_info/', views.dev_info, name='dev_info'),
    path('predict_f4/', views.predict_f4, name='f4_predict'),
    path('predict_b1/', views.predict_b1, name='b1_predict'),
    path('ratio_setting/', views.ratio_setting, name='ratio_predict'),
    path('DB_preprocessing/', views.DB_preprocessing, name='DB_preprocessing'),
    path('load_book_info/', views.load_book_info, name='load_book_info'),
    path('download_book_data/', sets.download_book_data, name='download_book_data'),
    path('load_book_data/', sets.load_book_data, name='load_book_data'),
    path('load_book_max_page_len/', sets.load_book_max_page_len, name='load_book_max_page_len'),
    path('save_add_book/', sets.save_add_book, name='save_add_book'),
    path('save_book_file/', sets.save_book_file, name='save_book_file'),
    path('edit_book/', sets.edit_book, name='edit_book'),
    path('download_rent_data/', sets.download_rent_data, name='download_rent_data'),
    path('load_rent_data/', sets.load_rent_data, name='load_rent_data'),
    path('load_rent_max_page_len/', sets.load_rent_max_page_len, name='load_rent_max_page_len'),
    path('except_download_book_data/', sets.except_download_book_data, name='except_download_book_data'),
    path('except_load_book_data/', sets.except_load_book_data, name='except_load_book_data'),
    path('except_load_book_max_page_len/', sets.except_load_book_max_page_len, name='except_load_book_max_page_len'),
    path('save_except_book_file/', sets.save_except_book_file, name='save_except_book_file'),
    path('load_book_info_predict/', predicts.load_book_info_predict, name='load_book_info_predict'),
    path('predict_book_lib/', predicts.predict_book_lib, name='predict_book_lib'),
    path('load_db_update/', predicts.load_db_update, name='load_db_update'),
    path('preprocessing_db/', predicts.preprocessing_db, name='preprocessing_db'),
    path('save_book_data/', predicts.save_book_data, name='save_book_data'),
    path('move_detail/', predicts.move_detail, name='move_detail'),
    path('load_book_max_page_len_detail/', predicts.load_book_max_page_len, name='load_book_max_page_len_detail'),
    path('load_book_data_detail/', predicts.load_book_data, name='load_book_data_detail'),
    path('download_book_data_detail/', predicts.download_book_data, name='download_book_data_detail'),
    path('predict_book_b1/', predicts.predict_book_b1, name='predict_book_b1'),
    path('setting_ratio/', predicts.setting_ratio, name='setting_ratio'),
    path('load_ratio/', predicts.load_ratio, name='load_ratio'),
]